
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import tkinter as tk
import loadsmwrh

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, StringVar, Frame, Label


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets/frame3")


def relative_to_assets(path: str) -> Path:
    print(ASSETS_PATH / Path(path)) 
    return ASSETS_PATH / Path(path)
    
def button_save_and_close(window,v1,v2):
    ohash = loadsmwrh.get_local_options()
    ohash['launcher1'] = v1.get()
    ohash['launcher2'] = v2.get()
    loadsmwrh.save_local_options(ohash)
    window.destroy()
    #

def launch_options_click(root):
    ohash = loadsmwrh.get_local_options()
    launcher1 = ohash['launcher1']
    launcher2 = ohash['launcher2']
         
    window = tk.Toplevel(root)
    window.geometry("734x484")
    window.configure(bg = "#FFFFFF")
    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 484,
        width = 734,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    canvas.create_text(
        87.0,
        81.0,
        anchor="nw",
        text="Game Launcher 1",
        fill="#000000",
        font=("Inter", 12 * -1)
    )

    entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_1 = canvas.create_image(
        418.0,
        97.0,
        image=entry_image_1
    )
    tvlauncher1 = StringVar(root,launcher1)
    tvlauncher2 = StringVar(root,launcher2)
    entry_1 = Entry(canvas,
        textvariable=tvlauncher1,
        bd=0,
        bg="#F1F5FF",
        fg="#000716",
        highlightthickness=0
    )
    entry_1.place(        
        x=238.0,
        y=69.0,
        width=360.0,
        height=54.0
    )
    
    canvas.create_text(
        87.0,
        190.0,
        anchor="nw",
        text="Game Launcher 2",
        fill="#000000",
        font=("Inter", 12 * -1)
)

    entry_image_2 = PhotoImage(
        file=relative_to_assets("entry_2.png"))
    entry_bg_2 = canvas.create_image(
        418.0,
        206.0,
        image=entry_image_2
    )
    entry_2 = Entry(canvas,
        bd=0,
        textvariable=tvlauncher2,
        bg="#F1F5FF",
        fg="#000716",
        highlightthickness=0
    )
    entry_2.place(
        x=238.0,
        y=178.0,
        width=360.0,
        height=54.0
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(canvas,
        text="Save and Close",
        #image=button_image_1,
        borderwidth=1,
        highlightthickness=1,
        command=lambda: button_save_and_close(window,tvlauncher1,tvlauncher2),
        #relief="flat"
    )
    button_1.place(
        x=97.0,
        y=400.0,
        width=122.0,
        height=47.0
    )
    window.resizable(False, False)
    window.grab_set()
    
    
