
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets/frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("734x484")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 484,
    width = 734,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    36.0,
    46.0,
    anchor="nw",
    text="Name",
    fill="#000000",
    font=("Inter", 12 * -1)
)

canvas.create_text(
    36.0,
    109.0,
    anchor="nw",
    text="Game Notes",
    fill="#000000",
    font=("Inter", 12 * -1)
)

canvas.create_text(
    186.0,
    261.0,
    anchor="nw",
    text="Completed",
    fill="#000000",
    font=("Inter", 12 * -1)
)

canvas.create_text(
    186.0,
    292.0,
    anchor="nw",
    text="Block and Hide Hack",
    fill="#000000",
    font=("Inter", 12 * -1)
)

canvas.create_text(
    186.0,
    323.0,
    anchor="nw",
    text="Exclude this game from random hack selection",
    fill="#000000",
    font=("Inter", 12 * -1)
)

canvas.create_text(
    186.0,
    366.0,
    anchor="nw",
    text="Exclude this game from random level selection",
    fill="#000000",
    font=("Inter", 12 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    367.0,
    135.5,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#F1F5FF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=187.0,
    y=100.0,
    width=360.0,
    height=69.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    367.0,
    53.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#F1F5FF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=187.0,
    y=25.0,
    width=360.0,
    height=54.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=64.0,
    y=415.0,
    width=122.0,
    height=47.0
)
window.resizable(False, False)
window.mainloop()
