CREATE TABLE attachments (
  auuid varchar(255) primary key DEFAULT (uuid()),
  pbuuid varchar(255),
  gvuuid varchar(255),
  resuuid varchar(255),
  file_crc16 varchar(255) NOT NULL,
  file_crc32 varchar(255) NOT NULL,
  locators text,
  parents text,
  file_ipfs_cidv0 varchar(255) NOT NULL,
  file_ipfs_cidv1 varchar(255) NOT NULL,
  file_hash_sha224 varchar(255) NOT NULL,
  file_hash_sha1 varchar(255) NOT NULL,
  file_hash_md5 varchar(255) NOT NULL,
  file_hash_sha256 varchar(255) NOT NULL,
  file_name varchar(255) NOT NULL,
  filekey varchar(255) NOT NULL,
  decoded_ipfs_cidv0 varchar(255) NOT NULL,
  decoded_ipfs_cidv1 varchar(255) NOT NULL,
  decoded_hash_sha224 varchar(255) NOT NULL,
  decoded_hash_sha1 varchar(255) NOT NULL,
  decoded_hash_md5 varchar(255) NOT NULL,
  decoded_hash_sha256 varchar(255) NOT NULL,
  updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  import_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  file_data blob,
  UNIQUE(file_name,file_hash_sha224)
)
